# Generated by Django 4.1.2 on 2022-10-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="snippet",
            name="email",
            field=models.CharField(default=False, max_length=254),
        ),
        migrations.AddField(
            model_name="snippet",
            name="p_num",
            field=models.CharField(default=False, max_length=10),
        ),
    ]
